### ISSUE TITLE
All links in gallery are broken and thumbnails not showing either

### ISSUE THREAD

**Issue by ssteinerx** [gcushen/mezzanine-api-docker#5]
For example:

  ./static/media/uploads/gallery/.thumbnails/Warsaw, Poland.jpg

exists, but the thumbnail doesn't show in the gallery, and the link itself 404's.

Unfortunately, in its broken state, attempting to repoint the file in the back-end also produces an error and the link can't be modified.

It looks like there is supposed to be a set of full-size files in the 'gallery' and the thumbnails are some sort of Mezzanine magic I'm not familiar with.

I'm guessing that the full-sized files are just missing from the Git repository?

Here's a snippet of the HTML:

```
<div class="col-xs-4 col-sm-3">
    <a class="thumbnail" rel="#image-1" title="Amsterdam  Holland" href="/static/media/uploads/gallery/Amsterdam%2C%20Holland.jpg">
        <img class="img-responsive" src="/static/media/uploads/gallery/Amsterdam, Holland.jpg">
    </a>
</div>
```

**Comment by gcushen** [comment]
I have not had a chance to review all the changes that the core Mezzanine team have made yet, but the following might point you in the right direction.

Mezzanine creates the demo gallery here at around line 108 `def create_pages(self):`: https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/management/commands/createdb.py 

Which should get called from the Docker project during database creation here: https://github.com/gcushen/mezzanine-api-docker/blob/master/web/start.sh

And the demo gallery images are located in the Zip file here: https://github.com/stephenmcd/mezzanine/tree/master/mezzanine/core/static/test

**Comment by ssteinerx** [comment]
The zip is there, Are they supposed to have been unzipped at some point?  Did I just miss a step?

**Comment by ssteinerx** [comment]
Was the zip file supposed to have been extracted to the ./static/media/uploads/gallery directory?  They are not there though the thumbnails are all there.

Did I miss a step, or is the initialization of the gallery supposed to also extract the .jpg files to the directory?

**Comment by ssteinerx** [comment]
It looks like BaseGallery's save() method is supposed to extract the files from the zip file, but they're not there.  

The .thumbnails directory is there, but the HTML incorrectly specifies the path to the thumbnail file in the:

```
<a class="thumbnail"...
```

hunk of HTML (it references the full-sized file instead).  Even if the full sized file were there, shoehorning it into the preview image size is the wrong way to do it so that seems like a Mezzanine bug.

It seems that the:

```
echo "Mezzanine microservice executing: createdb/migrate ..."
python3 manage.py createdb --noinput
```

Is creating the gallery page properly (except for the omission of the .thumbnail directory in the HTML), but is not actually unzipping the gallery.zip contents to the right place (or, any place, for that matter).

Do you think this is this a Mezzanine bug?  I've not used Mezzanine before, so I'm kind of floundering here...

**Comment by ssteinerx** [comment]
Filed in Mezzanine main repo -- this looks like a Mezzanine bug: [Mezzanine 1651](https://github.com/stephenmcd/mezzanine/issues/1651)

**Comment by ssteinerx** [comment]
Received this _incredibly_ helpful response from @stephenmcd who closed this an hour ago.

You don't have Pillow correctly installed.

I don't even know what that means, but it seems that something is not entirely set up in the Docker config.

**Comment by stephenmcd** [comment]
Thanks @gcushen
